name: "Release"
run-name: "Release (${{ inputs.action }})"
on:
  workflow_dispatch:
    inputs:
      action:
        description: "Release action to perform"
        type: choice
        options:
          - release-snapshot
          - verify-snapshot
          - release
          - verify
      packages_registry:
        description: "Maven packages registry to resolve release dependencies"
        required: true
        type: string
      releaser_repository:
        description: "GitHub repository that is performing the release (ORG/REPO)"
        required: true
        type: string
      releaser_ref:
        description: "Ref of the branch or tag performing the release"
        required: true
        type: string
permissions:
  contents: "read"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ inputs.action }}"
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    if: "${{ inputs.action != 'publish' }}"
    steps:
      - name: "Set up Java"
        id: "set-up-java"
        uses: "actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654" # 5.2.0
        with:
          distribution: "liberica"
          java-version: "25"
      - name: "Check Out Code"
        id: "check-out-code"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # 6.0.2
      - name: "Build"
        id: "build"
        uses: "./.github/actions/build"
        with:
          packages_registry: ${{ inputs.packages_registry }}
          create_deployment: "${{ (inputs.action == 'release-snapshot') || (inputs.action == 'release') }}"
          verify: "${{ (inputs.action == 'verify-snapshot') || (inputs.action == 'verify') }}"
      - name: "Publish"
        id: "publish"
        if: "${{ inputs.action == 'publish' }}"
        run: |
          echo "Published"
      - name: "Return"
        id: "return"
        if: ${{ !cancelled() }}
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.RELEASE_GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/${{ inputs.releaser_repository }}/actions/workflows/resume.yml/dispatches \
            -d '{"ref":"${{ inputs.releaser_ref }}","inputs":{"repository":"${{ github.repository }}", "run_id":"${{ github.run_id }}", "run_attempt":"${{ github.run_attempt }}"}}'
